---
title: "Week 6 Notes"
date: "2025-10-13"
---

## Key Concepts Learned
- Baseline Models
  * Coefficient of intercept = base price
  * Coefficient of extra variable = additional cost
  * p < 0.001 is statistically significant
  * Ignores spatial features like school quality and nearby crime levels
- Continuous Variables
  * Square footage, age of house, income levels, distance to downtown
- Categorical Variables
  * Neighborhood, school district, building type
- Interpreting Neighborhood Variables
  * Positive coefficient = neighborhood is more expensive
  * Negative coefficient = neighborhood is less expensive
- No Interaction/Parallel Slopes
  * Assumes that the added variable has the same effect in all neighborhoods
- With Interaction/Different Slopes
  * Assumes the added variable can have different effects in different neighborhoods
  * Should not be used in small samples or overfitting
- Buffer Aggregation
  * Count or sum events within a defined distance
- k-Nearest Neighbors
  * Average distance to k closest events
- Distance to Specific Points
  * Straight-line distance to important locations
- Fixed Effects
  * Categorical variables that capture all unmeasured characteristics of a group
  * Captures school quality, walkability, access to jobs - things we can't easily measure

## Coding Techniques
- Spatial Features
  * better_model <- lm(SalePrice ~ LivingArea + R_FULL_BTH, data = boston)
- Comparisons
  * cat("Baseline R:", summary(baseline_model)$r.squared, "\n")
- Convert to Spatial Data
  * boston.sf <- boston %>%
    * st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326) %>%
    * st_transform('ESRI:102286')  # MA State Plane (feet)
- Create Binary Indicator
  * boston.sf <- boston.sf %>%
    * mutate(wealthy_neighborhood = ifelse(name %in% wealthy_hoods, "Wealthy", "Not Wealthy"),wealthy_neighborhood = as.factor(wealthy_neighborhood))


## Questions & Challenges
- Challenged by everything!

## Connections to Policy
- Indicates different housing markets, affordability crisis, and ways to design policy

## Reflection
- Not sure I'm understanding this week.