project:
  type: website
  output-dir: docs

website:
  title: "Hope Levin - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Weekly Notes 
        menu:
          - href: weekly-notes/week-01-notes.qmd
            text: Week 1
          - href: weekly-notes/week-02-notes.qmd
            text: Week 2
      - text: Assignments 
        menu:
          - href: assignments/assignment_1/assignment1.qmd
            text: "Assignment 1: Census Data Exploration"
    
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
